name: Deploy Lambda with S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt -t app/

      - name: Package Lambda
        run: |
          cd app
          zip -r ../lambda_function.zip .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Deploy Infrastrutucture
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code --function-name fit-strike-api --zip-file fileb://lambda_function.zip

      - name: Wati for Lambda Update
        run: |
          aws lambda wait function-updated --function-name fit-strike-api

      - name: Version Lambda
        run: |
          aws lambda publish-version --function-name fit-strike-api