name: Deploy Infrastructure

on:
  push:
    branches:
      - main  # Executa o deploy ao fazer push na branch main

jobs:
  deploy-infra:
    name: Deploy Infrastructure to AWS
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Configurar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 4. Inicializar Terraform
    - name: Initialize Terraform
      run: |
        cd infra
        terraform init

    # 5. Planejar Terraform
    - name: Plan Terraform
      run: |
        cd infra
        terraform plan

    # 6. Aplicar Terraform
    - name: Apply Terraform
      run: |
        cd infra
        terraform apply -auto-approve

    # 7. Acionar o workflow de deploy da Lambda
    - name: Trigger Lambda Deploy Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: deploy-lambda