name: Deploy Lambda

on:
  push:
    branches:
      - main  # Executa o deploy ao fazer push na branch main

jobs:
  deploy:
    name: Deploy Lambda to AWS
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Instalar dependências na pasta package
    - name: Install dependencies
      run: |
        mkdir package
        pip install -r src/requirements.txt -t package/

    # 4. Copiar o código-fonte para a pasta package
    - name: Copy source code
      run: |
        cp -r src/* package/

    # 5. Empacotar o código e dependências
    - name: Package Lambda
      run: |
        cd package
        zip -r ../lambda_function.zip .
        cd ..

    # 6. Fazer o deploy da Lambda
    - name: Deploy Lambda
      run: |
        aws lambda update-function-code \
          --function-name fit-strike-api \
          --zip-file fileb://lambda_function.zip